package com.tobeto.pair5.a.Mernis;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.1
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 0BC3D78C8D7CC8969DA27BAB078C10C10E0217818805946BDD4FFC0CE108F7072CBB3DD8FA4C8DD78F0616D6AA2AB0B00688DA20AED9DB80968C475839DB9C63
//------------------------------------------------------------------------
import java.util.Date;


public interface GBFDateTimeConverter
{
    java.util.Date convertDateTime(String strDate);
    java.util.Date convertTime(String strDate);
    java.util.Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}